# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picrel',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438'),
        ),
    ]
