# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_picrel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picrel',
        ),
    ]
